optime_commtool_homepage:
    pattern:  /
    defaults: { _controller: OptimeCommtoolBundle:Default:index }
optime_commtool_update_sections:
    pattern:  /update
    defaults: { _controller: OptimeCommtoolBundle:Default:updateSections }
