parameters:
#    optime_commtool.example.class: Optime\Bundle\CommtoolBundle\Example

services:
    commtool_template_factory:
        class: Optime\Bundle\CommtoolBundle\TemplateFactory
        arguments: ["@commtool_control_factory"]
    commtool_control_factory:
        class: Optime\Bundle\CommtoolBundle\ControlFactory
        arguments: 
            - []
        calls: 
            - [setContainer, ["@service_container"]]
            - [setManipulator, ["@commtool_manipulator"]]
    commtool_manipulator:
        class: Optime\Bundle\CommtoolBundle\Template\Manipulator\PhpQueryManipulator
        factory_class: Optime\Bundle\CommtoolBundle\TemplateManipulatorFactory
        factory_method: get
        arguments: 
            - "@service_container"
            - phpquery