parameters:
#    optime_commtool.example.class: Optime\Bundle\CommtoolBundle\Example

services:
    commtool_template_factory:
        class: Optime\Bundle\CommtoolBundle\TemplateFactory
        arguments: ["@commtool_template_reader","@commtool_section_factory"]
    commtool_section_factory:
        class: Optime\Bundle\CommtoolBundle\SectionFactory
        calls: 
            - [setContainer, ["@service_container"]]
    commtool_template_reader_factory:
        class: Optime\Bundle\CommtoolBundle\TemplateReaderFactory
        arguments: ["@service_container"]
    commtool_template_reader:
        class: Optime\Bundle\CommtoolBundle\Reader\PhpQueryReader
        factory_class: Optime\Bundle\CommtoolBundle\TemplateReaderFactory
        factory_method: get
        arguments: 
            - "@service_container"
            - phpquery