parameters:

services:
    commtool_factory:
        class: Optime\Bundle\CommtoolBundle\CommtoolFactory
        arguments: ["@commtool_control_factory", "@twig"]
    commtool_control_factory:
        class: Optime\Bundle\CommtoolBundle\ControlFactory
        arguments: 
            - []
        calls: 
            - [setContainer, ["@service_container"]]
            - [setManipulator, ["@commtool_manipulator"]]
    commtool_manipulator:
        class: Optime\Bundle\CommtoolBundle\Template\Manipulator\PhpQueryManipulator
        factory_class: Optime\Bundle\CommtoolBundle\TemplateManipulatorFactory
        arguments: ["@commtool_control_factory"]
    commtool_twig_extension:
        class: Optime\Bundle\CommtoolBundle\Twig\Extension\CommtoolExtension
        tags:
            - {name: twig.extension}