services:
    commtool.control.singleline:
        class: Optime\Bundle\CommtoolBundle\Control\Singleline
        tags:
            - {name: commtool.control.type, alias: singleline}
    commtool.control.multiline:
        class: Optime\Bundle\CommtoolBundle\Control\Multiline
        tags:
            - {name: commtool.control.type, alias: multiline}
    commtool.control.image:
        class: Optime\Bundle\CommtoolBundle\Control\Image
        tags:
            - {name: commtool.control.type, alias: image}
    commtool.control.loop:
        class: Optime\Bundle\CommtoolBundle\Control\Loop
        tags:
            - {name: commtool.control.type, alias: loop}
    commtool.control.product:
        class: Optime\Bundle\CommtoolBundle\Control\Product
        arguments:
            - "@commtool_manipulator"
        tags:
            - {name: commtool.control.type, alias: product}