services:
    commtool.section.singleline:
        class: Optime\Bundle\CommtoolBundle\Section\Singleline
        tags:
            - {name: commtool.section.type, alias: singleline}
    commtool.section.multiline:
        class: Optime\Bundle\CommtoolBundle\Section\Multiline
        tags:
            - {name: commtool.section.type, alias: multiline}