services:
    commtool.section.singleline:
        class: Optime\Bundle\CommtoolBundle\Section\Singleline
        tags:
            - {name: commtool.section.type, alias: singleline}
    commtool.section.multiline:
        class: Optime\Bundle\CommtoolBundle\Section\Multiline
        tags:
            - {name: commtool.section.type, alias: multiline}
    commtool.section.loop:
        class: Optime\Bundle\CommtoolBundle\Section\Loop
        arguments:
            - "@commtool_manipulator"
        tags:
            - {name: commtool.section.type, alias: loop}